import { execSync } from "child_process";
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Extract all schema names from schema.d.ts
function extractSchemaNames(): string[] {
  const schemaPath = join(__dirname, "../src/schema.d.ts");
  const schemaContent = readFileSync(schemaPath, "utf-8");

  // Find the components.schemas interface
  const schemasBlockRegex =
    /export interface components \{[\s\S]*?schemas: \{([\s\S]*?)\n {2}\};/;
  const schemasMatch = schemaContent.match(schemasBlockRegex);

  if (!schemasMatch) {
    throw new Error("Could not find components.schemas in schema.d.ts");
  }

  const schemasBlock = schemasMatch[1];

  // Extract all schema names (they appear as property names followed by a colon)
  // Pattern: whitespace, schema name (word chars), colon, whitespace, opening brace
  const schemaNameRegex = /^\s{4}(\w+):\s*\{/gm;
  const schemaNames: string[] = [];
  let match;

  while ((match = schemaNameRegex.exec(schemasBlock)) !== null) {
    schemaNames.push(match[1]);
  }

  return schemaNames.sort();
}

// Generate the schemas.ts file content
function generateSchemasFile(schemaNames: string[]): string {
  const lines: string[] = [
    "/**",
    " * This file was auto-generated by scripts/generate-schemas.ts",
    " * Do not make direct changes to the file.",
    " */",
    "",
    'import { components } from "./schema";',
    "",
    'type Schemas = components["schemas"];',
    "",
  ];

  for (const schemaName of schemaNames) {
    lines.push(`export type ${schemaName} = Schemas["${schemaName}"];`);
  }

  lines.push("");

  return lines.join("\n");
}

// Main function
async function main() {
  console.log("🔍 Extracting schema names from schema.d.ts...");
  const schemaNames = extractSchemaNames();

  console.log(`📝 Found ${schemaNames.length} schemas`);

  // Generate schemas.ts file
  console.log("✨ Generating schemas.ts...");
  const content = generateSchemasFile(schemaNames);
  const outputPath = join(__dirname, "../src/schema-types.ts");
  writeFileSync(outputPath, content, "utf-8");
  console.log("  ✓ schema-types.ts");

  // Format generated file with prettier
  console.log("\n🎨 Formatting generated file with prettier...");
  execSync('pnpm prettier --write "src/schema-types.ts"', {
    cwd: join(__dirname, ".."),
    stdio: "inherit",
  });

  console.log(
    `\n✅ Successfully generated ${schemaNames.length} schema types!`,
  );
}

main().catch(console.error);
