/**
 * This file was auto-generated by scripts/generate-operations.ts
 * Do not make direct changes to the file.
 */

import type {
  FetchClient,
  PathParams,
  QueryParams,
  RequestBody,
} from "./client";

export function cancelAppointment(
  client: FetchClient,
  path: PathParams<"/v1/appointments/{appointment_id}/cancel", "post">,
  body: RequestBody<"/v1/appointments/{appointment_id}/cancel", "post">,
) {
  return client.POST("/v1/appointments/{appointment_id}/cancel", {
    body,
    params: { path },
  });
}

export function cancelPublicAppointment(
  client: FetchClient,
  path: PathParams<"/v1/public/appointments/{appointment_id}/cancel", "post">,
  body: RequestBody<"/v1/public/appointments/{appointment_id}/cancel", "post">,
) {
  return client.POST("/v1/public/appointments/{appointment_id}/cancel", {
    body,
    params: { path },
  });
}

export function confirmAppointment(
  client: FetchClient,
  path: PathParams<"/v1/appointments/{appointment_id}/confirm", "post">,
  body: RequestBody<"/v1/appointments/{appointment_id}/confirm", "post">,
) {
  return client.POST("/v1/appointments/{appointment_id}/confirm", {
    body,
    params: { path },
  });
}

export function createAccount(
  client: FetchClient,
  body: RequestBody<"/v1/accounts", "post">,
) {
  return client.POST("/v1/accounts", {
    body,
  });
}

export function createAccountUser(
  client: FetchClient,
  body: RequestBody<"/v1/users", "post">,
) {
  return client.POST("/v1/users", {
    body,
  });
}

export function createAppointment(
  client: FetchClient,
  body: RequestBody<"/v1/appointments", "post">,
) {
  return client.POST("/v1/appointments", {
    body,
  });
}

export function createBlock(
  client: FetchClient,
  body: RequestBody<"/v1/blocks", "post">,
) {
  return client.POST("/v1/blocks", {
    body,
  });
}

export function createCancellationReason(
  client: FetchClient,
  body: RequestBody<"/v1/cancellation_reasons", "post">,
) {
  return client.POST("/v1/cancellation_reasons", {
    body,
  });
}

export function createClient(
  client: FetchClient,
  body: RequestBody<"/v1/clients", "post">,
) {
  return client.POST("/v1/clients", {
    body,
  });
}

export function createDashboardSession(
  client: FetchClient,
  body: RequestBody<"/v1/dashboard_sessions", "post">,
) {
  return client.POST("/v1/dashboard_sessions", {
    body,
  });
}

export function createProvider(
  client: FetchClient,
  body: RequestBody<"/v1/providers", "post">,
) {
  return client.POST("/v1/providers", {
    body,
  });
}

export function createProviderSchedule(
  client: FetchClient,
  path: PathParams<"/v1/providers/{provider_id}/schedules", "post">,
  body: RequestBody<"/v1/providers/{provider_id}/schedules", "post">,
) {
  return client.POST("/v1/providers/{provider_id}/schedules", {
    body,
    params: { path },
  });
}

export function createPublicAppointment(
  client: FetchClient,
  body: RequestBody<"/v1/public/appointments", "post">,
) {
  return client.POST("/v1/public/appointments", {
    body,
  });
}

export function createService(
  client: FetchClient,
  body: RequestBody<"/v1/services", "post">,
) {
  return client.POST("/v1/services", {
    body,
  });
}

export function createServiceProvider(
  client: FetchClient,
  path: PathParams<"/v1/services/{service_id}/providers", "post">,
  body: RequestBody<"/v1/services/{service_id}/providers", "post">,
) {
  return client.POST("/v1/services/{service_id}/providers", {
    body,
    params: { path },
  });
}

export function deactivateProvider(
  client: FetchClient,
  path: PathParams<"/v1/providers/{provider_id}", "delete">,
) {
  return client.DELETE("/v1/providers/{provider_id}", {
    params: { path },
  });
}

export function deleteBlock(
  client: FetchClient,
  path: PathParams<"/v1/blocks/{block_id}", "delete">,
) {
  return client.DELETE("/v1/blocks/{block_id}", {
    params: { path },
  });
}

export function deleteCancellationReason(
  client: FetchClient,
  path: PathParams<
    "/v1/cancellation_reasons/{cancellation_reason_id}",
    "delete"
  >,
) {
  return client.DELETE("/v1/cancellation_reasons/{cancellation_reason_id}", {
    params: { path },
  });
}

export function deleteClient(
  client: FetchClient,
  path: PathParams<"/v1/clients/{client_id}", "delete">,
) {
  return client.DELETE("/v1/clients/{client_id}", {
    params: { path },
  });
}

export function deleteProviderSchedule(
  client: FetchClient,
  path: PathParams<"/v1/provider_schedules/{provider_schedule_id}", "delete">,
) {
  return client.DELETE("/v1/provider_schedules/{provider_schedule_id}", {
    params: { path },
  });
}

export function deleteService(
  client: FetchClient,
  path: PathParams<"/v1/services/{service_id}", "delete">,
) {
  return client.DELETE("/v1/services/{service_id}", {
    params: { path },
  });
}

export function deleteServiceProvider(
  client: FetchClient,
  path: PathParams<"/v1/service_providers/{service_provider_id}", "delete">,
) {
  return client.DELETE("/v1/service_providers/{service_provider_id}", {
    params: { path },
  });
}

export function getAccountById(
  client: FetchClient,
  path: PathParams<"/v1/accounts/{account_id}", "get">,
) {
  return client.GET("/v1/accounts/{account_id}", {
    params: { path },
  });
}

export function getAppointment(
  client: FetchClient,
  path: PathParams<"/v1/appointments/{appointment_id}", "get">,
  query?: QueryParams<"/v1/appointments/{appointment_id}", "get">,
) {
  return client.GET("/v1/appointments/{appointment_id}", {
    params: { path, query },
  });
}

export function getBlock(
  client: FetchClient,
  path: PathParams<"/v1/blocks/{block_id}", "get">,
) {
  return client.GET("/v1/blocks/{block_id}", {
    params: { path },
  });
}

export function getCancellationReason(
  client: FetchClient,
  path: PathParams<"/v1/cancellation_reasons/{cancellation_reason_id}", "get">,
) {
  return client.GET("/v1/cancellation_reasons/{cancellation_reason_id}", {
    params: { path },
  });
}

export function getClient(
  client: FetchClient,
  path: PathParams<"/v1/clients/{client_id}", "get">,
) {
  return client.GET("/v1/clients/{client_id}", {
    params: { path },
  });
}

export function getCurrentAccount(client: FetchClient) {
  return client.GET("/v1/account");
}

export function getCurrentAccountUser(client: FetchClient) {
  return client.GET("/v1/user");
}

export function getCurrentPlatform(client: FetchClient) {
  return client.GET("/v1/platform");
}

export function getEarliestPublicServiceSlot(
  client: FetchClient,
  path: PathParams<"/v1/public/services/{service_id}/earliest_slot", "get">,
  query?: QueryParams<"/v1/public/services/{service_id}/earliest_slot", "get">,
) {
  return client.GET("/v1/public/services/{service_id}/earliest_slot", {
    params: { path, query },
  });
}

export function getProvider(
  client: FetchClient,
  path: PathParams<"/v1/providers/{provider_id}", "get">,
) {
  return client.GET("/v1/providers/{provider_id}", {
    params: { path },
  });
}

export function getProviderSchedule(
  client: FetchClient,
  path: PathParams<"/v1/provider_schedules/{provider_schedule_id}", "get">,
) {
  return client.GET("/v1/provider_schedules/{provider_schedule_id}", {
    params: { path },
  });
}

export function getPublicAppointment(
  client: FetchClient,
  path: PathParams<"/v1/public/appointments/{appointment_id}", "get">,
) {
  return client.GET("/v1/public/appointments/{appointment_id}", {
    params: { path },
  });
}

export function getService(
  client: FetchClient,
  path: PathParams<"/v1/services/{service_id}", "get">,
) {
  return client.GET("/v1/services/{service_id}", {
    params: { path },
  });
}

export function listAccounts(
  client: FetchClient,
  query?: QueryParams<"/v1/accounts", "get">,
) {
  return client.GET("/v1/accounts", {
    params: { query },
  });
}

export function listAccountUsers(client: FetchClient) {
  return client.GET("/v1/users");
}

export function listAppointments(
  client: FetchClient,
  query?: QueryParams<"/v1/appointments", "get">,
) {
  return client.GET("/v1/appointments", {
    params: { query },
  });
}

export function listBlocks(
  client: FetchClient,
  query?: QueryParams<"/v1/blocks", "get">,
) {
  return client.GET("/v1/blocks", {
    params: { query },
  });
}

export function listCancellationReasons(client: FetchClient) {
  return client.GET("/v1/cancellation_reasons");
}

export function listClients(
  client: FetchClient,
  query?: QueryParams<"/v1/clients", "get">,
) {
  return client.GET("/v1/clients", {
    params: { query },
  });
}

export function listProviders(
  client: FetchClient,
  query?: QueryParams<"/v1/providers", "get">,
) {
  return client.GET("/v1/providers", {
    params: { query },
  });
}

export function listProviderSchedules(
  client: FetchClient,
  query?: QueryParams<"/v1/provider_schedules", "get">,
) {
  return client.GET("/v1/provider_schedules", {
    params: { query },
  });
}

export function listPublicCancellationReasons(
  client: FetchClient,
  path: PathParams<
    "/v1/public/appointments/{appointment_id}/cancellation_reasons",
    "get"
  >,
) {
  return client.GET(
    "/v1/public/appointments/{appointment_id}/cancellation_reasons",
    {
      params: { path },
    },
  );
}

export function listPublicServiceSlots(
  client: FetchClient,
  path: PathParams<"/v1/public/services/{service_id}/slots", "get">,
  query: QueryParams<"/v1/public/services/{service_id}/slots", "get">,
) {
  return client.GET("/v1/public/services/{service_id}/slots", {
    params: { path, query },
  });
}

export function listRoles(client: FetchClient) {
  return client.GET("/v1/roles");
}

export function listServiceProviders(
  client: FetchClient,
  path: PathParams<"/v1/services/{service_id}/providers", "get">,
) {
  return client.GET("/v1/services/{service_id}/providers", {
    params: { path },
  });
}

export function listServices(
  client: FetchClient,
  query?: QueryParams<"/v1/services", "get">,
) {
  return client.GET("/v1/services", {
    params: { query },
  });
}

export function listServiceSlots(
  client: FetchClient,
  path: PathParams<"/v1/services/{service_id}/slots", "get">,
  query: QueryParams<"/v1/services/{service_id}/slots", "get">,
) {
  return client.GET("/v1/services/{service_id}/slots", {
    params: { path, query },
  });
}

export function rescheduleAppointment(
  client: FetchClient,
  path: PathParams<"/v1/appointments/{appointment_id}/reschedule", "post">,
  body: RequestBody<"/v1/appointments/{appointment_id}/reschedule", "post">,
) {
  return client.POST("/v1/appointments/{appointment_id}/reschedule", {
    body,
    params: { path },
  });
}

export function reschedulePublicAppointment(
  client: FetchClient,
  path: PathParams<
    "/v1/public/appointments/{appointment_id}/reschedule",
    "post"
  >,
  body: RequestBody<
    "/v1/public/appointments/{appointment_id}/reschedule",
    "post"
  >,
) {
  return client.POST("/v1/public/appointments/{appointment_id}/reschedule", {
    body,
    params: { path },
  });
}

export function updateAccount(
  client: FetchClient,
  path: PathParams<"/v1/accounts/{account_id}", "patch">,
  body: RequestBody<"/v1/accounts/{account_id}", "patch">,
) {
  return client.PATCH("/v1/accounts/{account_id}", {
    body,
    params: { path },
  });
}

export function updateBlock(
  client: FetchClient,
  path: PathParams<"/v1/blocks/{block_id}", "patch">,
  body: RequestBody<"/v1/blocks/{block_id}", "patch">,
) {
  return client.PATCH("/v1/blocks/{block_id}", {
    body,
    params: { path },
  });
}

export function updateCancellationReason(
  client: FetchClient,
  path: PathParams<
    "/v1/cancellation_reasons/{cancellation_reason_id}",
    "patch"
  >,
  body: RequestBody<
    "/v1/cancellation_reasons/{cancellation_reason_id}",
    "patch"
  >,
) {
  return client.PATCH("/v1/cancellation_reasons/{cancellation_reason_id}", {
    body,
    params: { path },
  });
}

export function updateClient(
  client: FetchClient,
  path: PathParams<"/v1/clients/{client_id}", "patch">,
  body: RequestBody<"/v1/clients/{client_id}", "patch">,
) {
  return client.PATCH("/v1/clients/{client_id}", {
    body,
    params: { path },
  });
}

export function updateProvider(
  client: FetchClient,
  path: PathParams<"/v1/providers/{provider_id}", "patch">,
  body: RequestBody<"/v1/providers/{provider_id}", "patch">,
) {
  return client.PATCH("/v1/providers/{provider_id}", {
    body,
    params: { path },
  });
}

export function updateProviderSchedule(
  client: FetchClient,
  path: PathParams<"/v1/provider_schedules/{provider_schedule_id}", "patch">,
  body: RequestBody<"/v1/provider_schedules/{provider_schedule_id}", "patch">,
) {
  return client.PATCH("/v1/provider_schedules/{provider_schedule_id}", {
    body,
    params: { path },
  });
}

export function updateService(
  client: FetchClient,
  path: PathParams<"/v1/services/{service_id}", "patch">,
  body: RequestBody<"/v1/services/{service_id}", "patch">,
) {
  return client.PATCH("/v1/services/{service_id}", {
    body,
    params: { path },
  });
}
