/**
 * This file was auto-generated by scripts/generate-schemas.ts
 * Do not make direct changes to the file.
 */

import { components } from "./schema";

type Schemas = components["schemas"];

export type Account = Schemas["Account"];
export type AccountEvent = Schemas["AccountEvent"];
export type AccountResponse = Schemas["AccountResponse"];
export type AccountUser = Schemas["AccountUser"];
export type AccountUserResponse = Schemas["AccountUserResponse"];
export type AccountUsersResponse = Schemas["AccountUsersResponse"];
export type AccountsResponse = Schemas["AccountsResponse"];
export type AdvanceNoticePolicy = Schemas["AdvanceNoticePolicy"];
export type AggregatedSlot = Schemas["AggregatedSlot"];
export type Appointment = Schemas["Appointment"];
export type AppointmentCanceledEventData =
  Schemas["AppointmentCanceledEventData"];
export type AppointmentConfirmedEventData =
  Schemas["AppointmentConfirmedEventData"];
export type AppointmentCreatedEventData =
  Schemas["AppointmentCreatedEventData"];
export type AppointmentDeletedEventData =
  Schemas["AppointmentDeletedEventData"];
export type AppointmentRescheduledEventData =
  Schemas["AppointmentRescheduledEventData"];
export type AppointmentResponse = Schemas["AppointmentResponse"];
export type AppointmentsResponse = Schemas["AppointmentsResponse"];
export type Block = Schemas["Block"];
export type BlockResponse = Schemas["BlockResponse"];
export type BlocksResponse = Schemas["BlocksResponse"];
export type BookingPolicy = Schemas["BookingPolicy"];
export type CancelAppointmentRequest = Schemas["CancelAppointmentRequest"];
export type CancelPublicAppointmentRequest =
  Schemas["CancelPublicAppointmentRequest"];
export type CancellationEvent = Schemas["CancellationEvent"];
export type CancellationPolicy = Schemas["CancellationPolicy"];
export type CancellationReason = Schemas["CancellationReason"];
export type CancellationReasonResponse = Schemas["CancellationReasonResponse"];
export type CancellationReasonsResponse =
  Schemas["CancellationReasonsResponse"];
export type Client = Schemas["Client"];
export type ClientResponse = Schemas["ClientResponse"];
export type ClientsResponse = Schemas["ClientsResponse"];
export type ConfirmAppointmentRequest = Schemas["ConfirmAppointmentRequest"];
export type ConfirmationEvent = Schemas["ConfirmationEvent"];
export type CreateAccountRequest = Schemas["CreateAccountRequest"];
export type CreateAccountUserRequest = Schemas["CreateAccountUserRequest"];
export type CreateAppointmentRequest = Schemas["CreateAppointmentRequest"];
export type CreateBlockRequest = Schemas["CreateBlockRequest"];
export type CreateCancellationReasonRequest =
  Schemas["CreateCancellationReasonRequest"];
export type CreateClientRequest = Schemas["CreateClientRequest"];
export type CreateDashboardSessionRequest =
  Schemas["CreateDashboardSessionRequest"];
export type CreateProviderRequest = Schemas["CreateProviderRequest"];
export type CreateProviderScheduleRequest =
  Schemas["CreateProviderScheduleRequest"];
export type CreatePublicAppointmentRequest =
  Schemas["CreatePublicAppointmentRequest"];
export type CreateServiceProviderRequest =
  Schemas["CreateServiceProviderRequest"];
export type CreateServiceRequest = Schemas["CreateServiceRequest"];
export type DashboardSession = Schemas["DashboardSession"];
export type DashboardSessionResponse = Schemas["DashboardSessionResponse"];
export type GenericErrorResponse = Schemas["GenericErrorResponse"];
export type JsonErrorResponse = Schemas["JsonErrorResponse"];
export type MaximizeUtilizationPolicy = Schemas["MaximizeUtilizationPolicy"];
export type NotFoundResponse = Schemas["NotFoundResponse"];
export type PaginationMeta = Schemas["PaginationMeta"];
export type Platform = Schemas["Platform"];
export type PlatformResponse = Schemas["PlatformResponse"];
export type Provider = Schemas["Provider"];
export type ProviderResponse = Schemas["ProviderResponse"];
export type ProviderSchedule = Schemas["ProviderSchedule"];
export type ProviderScheduleResponse = Schemas["ProviderScheduleResponse"];
export type ProviderSchedulesResponse = Schemas["ProviderSchedulesResponse"];
export type ProvidersResponse = Schemas["ProvidersResponse"];
export type PublicAppointment = Schemas["PublicAppointment"];
export type PublicAppointmentResponse = Schemas["PublicAppointmentResponse"];
export type PublicCancellationReason = Schemas["PublicCancellationReason"];
export type PublicCancellationReasonsResponse =
  Schemas["PublicCancellationReasonsResponse"];
export type PublicServiceSlotsResponse = Schemas["PublicServiceSlotsResponse"];
export type RecurrenceRule = Schemas["RecurrenceRule"];
export type RescheduleAppointmentRequest =
  Schemas["RescheduleAppointmentRequest"];
export type RescheduleEvent = Schemas["RescheduleEvent"];
export type ReschedulePublicAppointmentRequest =
  Schemas["ReschedulePublicAppointmentRequest"];
export type ReschedulingPolicy = Schemas["ReschedulingPolicy"];
export type Role = Schemas["Role"];
export type RolesResponse = Schemas["RolesResponse"];
export type Service = Schemas["Service"];
export type ServiceProvider = Schemas["ServiceProvider"];
export type ServiceProviderResponse = Schemas["ServiceProviderResponse"];
export type ServiceProvidersResponse = Schemas["ServiceProvidersResponse"];
export type ServiceResponse = Schemas["ServiceResponse"];
export type ServiceSlotResponse = Schemas["ServiceSlotResponse"];
export type ServicesResponse = Schemas["ServicesResponse"];
export type Slot = Schemas["Slot"];
export type SlotRule = Schemas["SlotRule"];
export type UnauthorizedResponse = Schemas["UnauthorizedResponse"];
export type UpdateAccountRequest = Schemas["UpdateAccountRequest"];
export type UpdateBlockRequest = Schemas["UpdateBlockRequest"];
export type UpdateCancellationReasonRequest =
  Schemas["UpdateCancellationReasonRequest"];
export type UpdateClientRequest = Schemas["UpdateClientRequest"];
export type UpdateProviderRequest = Schemas["UpdateProviderRequest"];
export type UpdateProviderScheduleRequest =
  Schemas["UpdateProviderScheduleRequest"];
export type UpdateServiceRequest = Schemas["UpdateServiceRequest"];
export type User = Schemas["User"];
export type WeeklyRule = Schemas["WeeklyRule"];
export type ZonedDateTime = Schemas["ZonedDateTime"];
