import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/savvycal-appointments-api",
    },
    {
      type: "category",
      label: "Appointments",
      link: {
        type: "doc",
        id: "api/appointments",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/appointment",
          label: "Appointment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-appointment",
          label: "Get appointment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/confirm-appointment",
          label: "Confirm appointment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-appointments",
          label: "List appointments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-appointment",
          label: "Create appointment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reschedule-appointment",
          label: "Reschedule appointment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/cancel-appointment",
          label: "Cancel appointment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard Sessions",
      link: {
        type: "doc",
        id: "api/dashboard-sessions",
      },
      items: [
        {
          type: "doc",
          id: "api/create-dashboard-session",
          label: "Create dashboard session",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Accounts",
      link: {
        type: "doc",
        id: "api/accounts",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/account",
          label: "Account",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/list-accounts",
          label: "List accounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-account",
          label: "Create account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-account-by-id",
          label: "Get account by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-account",
          label: "Update account",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-current-account",
          label: "Get current account",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Provider Schedules",
      link: {
        type: "doc",
        id: "api/provider-schedules",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/providerschedule",
          label: "ProviderSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/delete-provider-schedule",
          label: "Delete provider schedule",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-provider-schedule",
          label: "Get provider schedule",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-provider-schedule",
          label: "Update provider schedule",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/create-provider-schedule",
          label: "Create provider schedule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-provider-schedules",
          label: "List provider schedules",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Public Booking",
      link: {
        type: "doc",
        id: "api/public-booking",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/publicappointment",
          label: "PublicAppointment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/create-public-appointment",
          label: "Create appointment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-public-appointment",
          label: "Get appointment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/cancel-public-appointment",
          label: "Cancel appointment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-public-cancellation-reasons",
          label: "List cancellation reasons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-earliest-public-service-slot",
          label: "Get earliest available slot",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reschedule-public-appointment",
          label: "Reschedule appointment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-public-service-slots",
          label: "List available time slots",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Clients",
      link: {
        type: "doc",
        id: "api/clients",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/client",
          label: "Client",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/delete-client",
          label: "Delete client",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-client",
          label: "Get client",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-client",
          label: "Update client",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/list-clients",
          label: "List clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-client",
          label: "Create client",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Services",
      link: {
        type: "doc",
        id: "api/services",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/service",
          label: "Service",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/delete-service",
          label: "Delete service",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-service",
          label: "Get service",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-service",
          label: "Update service",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/list-service-providers",
          label: "List service providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-service-provider",
          label: "Add provider to service",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-services",
          label: "List services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-service",
          label: "Create service",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-service-provider",
          label: "Remove service provider",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Cancellation Reasons",
      link: {
        type: "doc",
        id: "api/cancellation-reasons",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/cancellationreason",
          label: "CancellationReason",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/delete-cancellation-reason",
          label: "Delete cancellation reason",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-cancellation-reason",
          label: "Get cancellation reason",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-cancellation-reason",
          label: "Update cancellation reason",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/list-cancellation-reasons",
          label: "List cancellation reasons",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-cancellation-reason",
          label: "Create cancellation reason",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Roles",
      link: {
        type: "doc",
        id: "api/roles",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/list-roles",
          label: "List roles",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Providers",
      link: {
        type: "doc",
        id: "api/providers",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/provider",
          label: "Provider",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/list-providers",
          label: "List providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-provider",
          label: "Create provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/deactivate-provider",
          label: "Deactivate provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-provider",
          label: "Get provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-provider",
          label: "Update provider",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Account Users",
      link: {
        type: "doc",
        id: "api/account-users",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/accountuser",
          label: "AccountUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-current-account-user",
          label: "Get current account user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-account-users",
          label: "List account users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-account-user",
          label: "Create account user",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Platforms",
      link: {
        type: "doc",
        id: "api/platforms",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/platform",
          label: "Platform",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-current-platform",
          label: "Get current platform",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Blocks",
      link: {
        type: "doc",
        id: "api/blocks",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/block",
          label: "Block",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/delete-block",
          label: "Delete block",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-block",
          label: "Get block",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-block",
          label: "Update block",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/list-blocks",
          label: "List blocks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-block",
          label: "Create block",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Time Slots",
      link: {
        type: "doc",
        id: "api/time-slots",
      },
      items: [
        {
          type: "doc",
          id: "api/list-service-slots",
          label: "List available time slots",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/updateproviderschedulerequest",
          label: "UpdateProviderScheduleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/confirmationevent",
          label: "ConfirmationEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/blocksresponse",
          label: "BlocksResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appointmentrescheduledeventdata",
          label: "AppointmentRescheduledEventData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/serviceslotresponse",
          label: "ServiceSlotResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/confirmappointmentrequest",
          label: "ConfirmAppointmentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateblockrequest",
          label: "UpdateBlockRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/accountresponse",
          label: "AccountResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/genericerrorresponse",
          label: "GenericErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cancelpublicappointmentrequest",
          label: "CancelPublicAppointmentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/dashboardsessionresponse",
          label: "DashboardSessionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/serviceprovidersresponse",
          label: "ServiceProvidersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createproviderrequest",
          label: "CreateProviderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/serviceprovider",
          label: "ServiceProvider",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/paginationmeta",
          label: "PaginationMeta",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/serviceresponse",
          label: "ServiceResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createcancellationreasonrequest",
          label: "CreateCancellationReasonRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rescheduleevent",
          label: "RescheduleEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createaccountuserrequest",
          label: "CreateAccountUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rolesresponse",
          label: "RolesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createserviceproviderrequest",
          label: "CreateServiceProviderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cancellationpolicy",
          label: "CancellationPolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/publicserviceearliestslotresponse",
          label: "PublicServiceEarliestSlotResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateproviderrequest",
          label: "UpdateProviderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/publiccancellationreason",
          label: "PublicCancellationReason",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/reschedulepublicappointmentrequest",
          label: "ReschedulePublicAppointmentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/slotrule",
          label: "SlotRule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/publicserviceslotsresponse",
          label: "PublicServiceSlotsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/platformresponse",
          label: "PlatformResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/accountuserresponse",
          label: "AccountUserResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appointmentconfirmedeventdata",
          label: "AppointmentConfirmedEventData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cancellationreasonresponse",
          label: "CancellationReasonResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/clientsresponse",
          label: "ClientsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/slot",
          label: "Slot",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/accountevent",
          label: "AccountEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appointmentsresponse",
          label: "AppointmentsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateservicerequest",
          label: "UpdateServiceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateclientrequest",
          label: "UpdateClientRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/dashboardsession",
          label: "DashboardSession",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createblockrequest",
          label: "CreateBlockRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appointmentresponse",
          label: "AppointmentResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/clientresponse",
          label: "ClientResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/serviceproviderresponse",
          label: "ServiceProviderResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/emptyresponse",
          label: "EmptyResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateaccountrequest",
          label: "UpdateAccountRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/providersresponse",
          label: "ProvidersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/bookingpolicy",
          label: "BookingPolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/providerresponse",
          label: "ProviderResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/providerschedulesresponse",
          label: "ProviderSchedulesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/notfoundresponse",
          label: "NotFoundResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/publiccancellationreasonsresponse",
          label: "PublicCancellationReasonsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cancelappointmentrequest",
          label: "CancelAppointmentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cancellationevent",
          label: "CancellationEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cancellationreasonsresponse",
          label: "CancellationReasonsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/servicesresponse",
          label: "ServicesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/reschedulingpolicy",
          label: "ReschedulingPolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/providerscheduleresponse",
          label: "ProviderScheduleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/advancenoticepolicy",
          label: "AdvanceNoticePolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appointmentcanceledeventdata",
          label: "AppointmentCanceledEventData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createdashboardsessionrequest",
          label: "CreateDashboardSessionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createproviderschedulerequest",
          label: "CreateProviderScheduleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/recurrencerule",
          label: "RecurrenceRule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/accountsresponse",
          label: "AccountsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/weeklyrule",
          label: "WeeklyRule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/maximizeutilizationpolicy",
          label: "MaximizeUtilizationPolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createaccountrequest",
          label: "CreateAccountRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createappointmentrequest",
          label: "CreateAppointmentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appointmentdeletedeventdata",
          label: "AppointmentDeletedEventData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/unauthorizedresponse",
          label: "UnauthorizedResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createpublicappointmentrequest",
          label: "CreatePublicAppointmentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatecancellationreasonrequest",
          label: "UpdateCancellationReasonRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/blockresponse",
          label: "BlockResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/jsonerrorresponse",
          label: "JsonErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/publicappointmentresponse",
          label: "PublicAppointmentResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/aggregatedslot",
          label: "AggregatedSlot",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/accountusersresponse",
          label: "AccountUsersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createservicerequest",
          label: "CreateServiceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/appointmentcreatedeventdata",
          label: "AppointmentCreatedEventData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rescheduleappointmentrequest",
          label: "RescheduleAppointmentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createclientrequest",
          label: "CreateClientRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/zoneddatetime",
          label: "ZonedDateTime",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
