/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type AccountByIdParams =
  paths["/v1/accounts/{account_id}"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/accounts/{account_id}"> {
  client?: QueryClient;
}

export const useAccountById = (
  account_id: AccountByIdParams["path"]["account_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/accounts/{account_id}",
    {
      params: {
        path: { account_id },
      },
    },
    queryOptions,
  );
};
