/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type PublicServiceSlotsParams =
  paths["/v1/public/services/{service_id}/slots"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<"get", "/v1/public/services/{service_id}/slots"> {
  client?: QueryClient;
}

export const usePublicServiceSlots = (
  service_id: PublicServiceSlotsParams["path"]["service_id"],
  queryParams: PublicServiceSlotsParams["query"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/public/services/{service_id}/slots",
    {
      params: {
        path: { service_id },
        query: queryParams,
      },
    },
    queryOptions,
  );
};
