/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type RolesParams = paths["/v1/roles"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/roles"> {
  client?: QueryClient;
}

export const useRoles = (options?: Options) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery("get", "/v1/roles", {}, queryOptions);
};
