/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type AppointmentParams =
  paths["/v1/appointments/{appointment_id}"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useAppointment = (
  appointment_id: AppointmentParams["path"]["appointment_id"],
  queryParams?: AppointmentParams["query"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/appointments/{appointment_id}",
    {
      params: {
        path: { appointment_id },
        query: queryParams,
      },
    },
    { enabled: options?.enabled },
  );
};
