/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type EarliestPublicServiceSlotParams =
  paths["/v1/public/services/{service_id}/earliest_slot"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<
    "get",
    "/v1/public/services/{service_id}/earliest_slot"
  > {
  client?: QueryClient;
}

export const useEarliestPublicServiceSlot = (
  service_id: EarliestPublicServiceSlotParams["path"]["service_id"],
  queryParams?: EarliestPublicServiceSlotParams["query"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/public/services/{service_id}/earliest_slot",
    {
      params: {
        path: { service_id },
        query: queryParams,
      },
    },
    queryOptions,
  );
};
