/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";

import type { Client, QueryOptionsFor } from "../client";

import { useSavvyCalClient } from "../provider";

export type BlockParams = paths["/v1/blocks/{block_id}"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/blocks/{block_id}"> {
  client?: Client;
}

export const useBlock = (
  block_id: BlockParams["path"]["block_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/blocks/{block_id}",
    {
      params: {
        path: { block_id },
      },
    },
    queryOptions,
  );
};
