/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type ServiceProvidersParams =
  paths["/v1/services/{service_id}/providers"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useServiceProviders = (
  service_id: ServiceProvidersParams["path"]["service_id"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/services/{service_id}/providers",
    {
      params: {
        path: { service_id },
      },
    },
    { enabled: options?.enabled },
  );
};
