/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type CancellationReasonParams =
  paths["/v1/cancellation_reasons/{cancellation_reason_id}"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<
    "get",
    "/v1/cancellation_reasons/{cancellation_reason_id}"
  > {
  client?: QueryClient;
}

export const useCancellationReason = (
  cancellation_reason_id: CancellationReasonParams["path"]["cancellation_reason_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/cancellation_reasons/{cancellation_reason_id}",
    {
      params: {
        path: { cancellation_reason_id },
      },
    },
    queryOptions,
  );
};
