/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";

import type { Client, QueryOptionsFor } from "../client";

import { useSavvyCalClient } from "../provider";

export type ClientParams =
  paths["/v1/clients/{client_id}"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/clients/{client_id}"> {
  client?: Client;
}

export const useClient = (
  client_id: ClientParams["path"]["client_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/clients/{client_id}",
    {
      params: {
        path: { client_id },
      },
    },
    queryOptions,
  );
};
