/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client, QueryOptionsFor } from "../client";

export type BlocksParams = paths["/v1/blocks"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/blocks"> {
  client?: Client;
}

export const useBlocks = (
  queryParams?: BlocksParams["query"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/blocks",
    {
      params: {
        query: queryParams,
      },
    },
    queryOptions,
  );
};
