/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client, QueryOptionsFor } from "../client";

export type ServiceProvidersParams =
  paths["/v1/services/{service_id}/providers"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<"get", "/v1/services/{service_id}/providers"> {
  client?: Client;
}

export const useServiceProviders = (
  service_id: ServiceProvidersParams["path"]["service_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/services/{service_id}/providers",
    {
      params: {
        path: { service_id },
      },
    },
    queryOptions,
  );
};
