/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";

import type { Client, QueryOptionsFor } from "../client";

import { useSavvyCalClient } from "../provider";

export type ServiceParams =
  paths["/v1/services/{service_id}"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/services/{service_id}"> {
  client?: Client;
}

export const useService = (
  service_id: ServiceParams["path"]["service_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/services/{service_id}",
    {
      params: {
        path: { service_id },
      },
    },
    queryOptions,
  );
};
