/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type CurrentAccountParams = paths["/v1/account"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useCurrentAccount = (options?: Options) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/account",
    {},
    { enabled: options?.enabled },
  );
};
