/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";

import type { Client, QueryOptionsFor } from "../client";

import { useSavvyCalClient } from "../provider";

export type AccountUsersParams = paths["/v1/users"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/users"> {
  client?: Client;
}

export const useAccountUsers = (options?: Options) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery("get", "/v1/users", {}, queryOptions);
};
