/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type ProviderParams =
  paths["/v1/providers/{provider_id}"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<"get", "/v1/providers/{provider_id}"> {
  client?: QueryClient;
}

export const useProvider = (
  provider_id: ProviderParams["path"]["provider_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/providers/{provider_id}",
    {
      params: {
        path: { provider_id },
      },
    },
    queryOptions,
  );
};
