/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type ProviderScheduleParams =
  paths["/v1/provider_schedules/{provider_schedule_id}"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useProviderSchedule = (
  provider_schedule_id: ProviderScheduleParams["path"]["provider_schedule_id"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/provider_schedules/{provider_schedule_id}",
    {
      params: {
        path: { provider_schedule_id },
      },
    },
    { enabled: options?.enabled },
  );
};
