/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type ProviderScheduleParams =
  paths["/v1/provider_schedules/{provider_schedule_id}"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<
    "get",
    "/v1/provider_schedules/{provider_schedule_id}"
  > {
  client?: QueryClient;
}

export const useProviderSchedule = (
  provider_schedule_id: ProviderScheduleParams["path"]["provider_schedule_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/provider_schedules/{provider_schedule_id}",
    {
      params: {
        path: { provider_schedule_id },
      },
    },
    queryOptions,
  );
};
