/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";

import type { Client, QueryOptionsFor } from "../client";

import { useSavvyCalClient } from "../provider";

export type ProviderSchedulesParams =
  paths["/v1/provider_schedules"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/provider_schedules"> {
  client?: Client;
}

export const useProviderSchedules = (
  queryParams?: ProviderSchedulesParams["query"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/provider_schedules",
    {
      params: {
        query: queryParams,
      },
    },
    queryOptions,
  );
};
