/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type ClientParams =
  paths["/v1/clients/{client_id}"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useClient = (
  client_id: ClientParams["path"]["client_id"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/clients/{client_id}",
    {
      params: {
        path: { client_id },
      },
    },
    { enabled: options?.enabled },
  );
};
