/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { UseQueryResult } from "@tanstack/react-query";
import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type PublicCancellationReasonsParams =
  paths["/v1/public/appointments/{appointment_id}/cancellation_reasons"]["get"]["parameters"];

type PublicCancellationReasonsData =
  paths["/v1/public/appointments/{appointment_id}/cancellation_reasons"]["get"]["responses"][200]["content"]["application/json"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const usePublicCancellationReasons = (
  appointment_id: PublicCancellationReasonsParams["path"]["appointment_id"],
  options?: Options,
): UseQueryResult<PublicCancellationReasonsData, unknown> => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/public/appointments/{appointment_id}/cancellation_reasons",
    {
      params: {
        path: { appointment_id },
      },
    },
    { enabled: options?.enabled },
  );
};
