/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type AppointmentParams =
  paths["/v1/appointments/{appointment_id}"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<"get", "/v1/appointments/{appointment_id}"> {
  client?: QueryClient;
}

export const useAppointment = (
  appointment_id: AppointmentParams["path"]["appointment_id"],
  queryParams?: AppointmentParams["query"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/appointments/{appointment_id}",
    {
      params: {
        path: { appointment_id },
        query: queryParams,
      },
    },
    queryOptions,
  );
};
