/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type BlockParams = paths["/v1/blocks/{block_id}"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useBlock = (
  block_id: BlockParams["path"]["block_id"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/blocks/{block_id}",
    {
      params: {
        path: { block_id },
      },
    },
    { enabled: options?.enabled },
  );
};
