/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client, QueryOptionsFor } from "../client";

export type AppointmentsParams = paths["/v1/appointments"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/appointments"> {
  client?: Client;
}

export const useAppointments = (
  queryParams?: AppointmentsParams["query"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/appointments",
    {
      params: {
        query: queryParams,
      },
    },
    queryOptions,
  );
};
