/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type AppointmentsParams = paths["/v1/appointments"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useAppointments = (
  queryParams?: AppointmentsParams["query"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/appointments",
    {
      params: {
        query: queryParams,
      },
    },
    { enabled: options?.enabled },
  );
};
