/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { paths } from "@savvycal/appointments-core";

import type { QueryClient, QueryOptionsFor } from "../client";

import { useSavvyCalQueryClient } from "../provider";

export type CurrentAccountUserParams = paths["/v1/user"]["get"]["parameters"];

interface Options extends QueryOptionsFor<"get", "/v1/user"> {
  client?: QueryClient;
}

export const useCurrentAccountUser = (options?: Options) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalQueryClient(overrideClient);

  return client.useQuery("get", "/v1/user", {}, queryOptions);
};
