/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type AccountByIdParams =
  paths["/v1/accounts/{account_id}"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useAccountById = (
  account_id: AccountByIdParams["path"]["account_id"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/accounts/{account_id}",
    {
      params: {
        path: { account_id },
      },
    },
    { enabled: options?.enabled },
  );
};
