/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client, QueryOptionsFor } from "../client";

export type PublicAppointmentParams =
  paths["/v1/public/appointments/{appointment_id}"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<"get", "/v1/public/appointments/{appointment_id}"> {
  client?: Client;
}

export const usePublicAppointment = (
  appointment_id: PublicAppointmentParams["path"]["appointment_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/public/appointments/{appointment_id}",
    {
      params: {
        path: { appointment_id },
      },
    },
    queryOptions,
  );
};
