/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type PublicServiceSlotsParams =
  paths["/v1/public/services/{service_id}/slots"]["get"]["parameters"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const usePublicServiceSlots = (
  service_id: PublicServiceSlotsParams["path"]["service_id"],
  queryParams: PublicServiceSlotsParams["query"],
  options?: Options,
) => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/public/services/{service_id}/slots",
    {
      params: {
        path: { service_id },
        query: queryParams,
      },
    },
    { enabled: options?.enabled },
  );
};
