/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";

import type { Client, QueryOptionsFor } from "../client";

import { useSavvyCalClient } from "../provider";

export type PublicCancellationReasonsParams =
  paths["/v1/public/appointments/{appointment_id}/cancellation_reasons"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<
    "get",
    "/v1/public/appointments/{appointment_id}/cancellation_reasons"
  > {
  client?: Client;
}

export const usePublicCancellationReasons = (
  appointment_id: PublicCancellationReasonsParams["path"]["appointment_id"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/public/appointments/{appointment_id}/cancellation_reasons",
    {
      params: {
        path: { appointment_id },
      },
    },
    queryOptions,
  );
};
