/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import type { UseQueryResult } from "@tanstack/react-query";
import { paths } from "@savvycal/appointments-core";
import { useSavvyCalClient } from "../provider";
import type { Client } from "../client";

export type AccountsParams = paths["/v1/accounts"]["get"]["parameters"];

type AccountsData =
  paths["/v1/accounts"]["get"]["responses"][200]["content"]["application/json"];

interface Options {
  client?: Client;
  enabled?: boolean;
}

export const useAccounts = (
  queryParams?: AccountsParams["query"],
  options?: Options,
): UseQueryResult<AccountsData, unknown> => {
  const client = useSavvyCalClient(options?.client);

  return client.useQuery(
    "get",
    "/v1/accounts",
    {
      params: {
        query: queryParams,
      },
    },
    { enabled: options?.enabled },
  );
};
