/**
 * This file was auto-generated by scripts/generate-query-hooks.ts
 * Do not make direct changes to the file.
 */

import { paths } from "@savvycal/appointments-core";

import type { Client, QueryOptionsFor } from "../client";

import { useSavvyCalClient } from "../provider";

export type ServiceSlotsParams =
  paths["/v1/services/{service_id}/slots"]["get"]["parameters"];

interface Options
  extends QueryOptionsFor<"get", "/v1/services/{service_id}/slots"> {
  client?: Client;
}

export const useServiceSlots = (
  service_id: ServiceSlotsParams["path"]["service_id"],
  queryParams: ServiceSlotsParams["query"],
  options?: Options,
) => {
  const { client: overrideClient, ...queryOptions } = options ?? {};
  const client = useSavvyCalClient(overrideClient);

  return client.useQuery(
    "get",
    "/v1/services/{service_id}/slots",
    {
      params: {
        path: { service_id },
        query: queryParams,
      },
    },
    queryOptions,
  );
};
