/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PublicBookingFormRouteImport } from "./routes/public-booking-form";

const PublicBookingFormRoute = PublicBookingFormRouteImport.update({
  id: "/public-booking-form",
  path: "/public-booking-form",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/public-booking-form": typeof PublicBookingFormRoute;
}
export interface FileRoutesByTo {
  "/public-booking-form": typeof PublicBookingFormRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/public-booking-form": typeof PublicBookingFormRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/public-booking-form";
  fileRoutesByTo: FileRoutesByTo;
  to: "/public-booking-form";
  id: "__root__" | "/public-booking-form";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PublicBookingFormRoute: typeof PublicBookingFormRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/public-booking-form": {
      id: "/public-booking-form";
      path: "/public-booking-form";
      fullPath: "/public-booking-form";
      preLoaderRoute: typeof PublicBookingFormRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  PublicBookingFormRoute: PublicBookingFormRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
