// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  CancelAppointmentData,
  CancelAppointmentErrors,
  CancelAppointmentResponses,
  ConfirmAppointmentData,
  ConfirmAppointmentErrors,
  ConfirmAppointmentResponses,
  CreateAccountData,
  CreateAccountErrors,
  CreateAccountResponses,
  CreateAccountUserData,
  CreateAccountUserErrors,
  CreateAccountUserResponses,
  CreateAppointmentData,
  CreateAppointmentErrors,
  CreateAppointmentResponses,
  CreateBlockData,
  CreateBlockErrors,
  CreateBlockResponses,
  CreateCancellationReasonData,
  CreateCancellationReasonErrors,
  CreateCancellationReasonResponses,
  CreateClientData,
  CreateClientErrors,
  CreateClientResponses,
  CreateDashboardSessionData,
  CreateDashboardSessionErrors,
  CreateDashboardSessionResponses,
  CreateProviderData,
  CreateProviderErrors,
  CreateProviderResponses,
  CreateProviderScheduleData,
  CreateProviderScheduleErrors,
  CreateProviderScheduleResponses,
  CreateServiceData,
  CreateServiceErrors,
  CreateServiceProviderData,
  CreateServiceProviderErrors,
  CreateServiceProviderResponses,
  CreateServiceResponses,
  DeactivateProviderData,
  DeactivateProviderErrors,
  DeactivateProviderResponses,
  DeleteBlockData,
  DeleteBlockErrors,
  DeleteBlockResponses,
  DeleteCancellationReasonData,
  DeleteCancellationReasonErrors,
  DeleteCancellationReasonResponses,
  DeleteClientData,
  DeleteClientErrors,
  DeleteClientResponses,
  DeleteProviderScheduleData,
  DeleteProviderScheduleErrors,
  DeleteProviderScheduleResponses,
  DeleteServiceData,
  DeleteServiceErrors,
  DeleteServiceProviderData,
  DeleteServiceProviderErrors,
  DeleteServiceProviderResponses,
  DeleteServiceResponses,
  GetAccountByIdData,
  GetAccountByIdErrors,
  GetAccountByIdResponses,
  GetAppointmentData,
  GetAppointmentErrors,
  GetAppointmentResponses,
  GetBlockData,
  GetBlockErrors,
  GetBlockResponses,
  GetCancellationReasonData,
  GetCancellationReasonErrors,
  GetCancellationReasonResponses,
  GetClientData,
  GetClientErrors,
  GetClientResponses,
  GetCurrentAccountData,
  GetCurrentAccountErrors,
  GetCurrentAccountResponses,
  GetCurrentPlatformData,
  GetCurrentPlatformErrors,
  GetCurrentPlatformResponses,
  GetProviderData,
  GetProviderErrors,
  GetProviderResponses,
  GetProviderScheduleData,
  GetProviderScheduleErrors,
  GetProviderScheduleResponses,
  GetServiceData,
  GetServiceErrors,
  GetServiceResponses,
  ListAccountsData,
  ListAccountsErrors,
  ListAccountsResponses,
  ListAccountUsersData,
  ListAccountUsersErrors,
  ListAccountUsersResponses,
  ListAppointmentsData,
  ListAppointmentsErrors,
  ListAppointmentsResponses,
  ListBlocksData,
  ListBlocksErrors,
  ListBlocksResponses,
  ListCancellationReasonsData,
  ListCancellationReasonsErrors,
  ListCancellationReasonsResponses,
  ListClientsData,
  ListClientsErrors,
  ListClientsResponses,
  ListProviderSchedulesData,
  ListProviderSchedulesErrors,
  ListProviderSchedulesResponses,
  ListProvidersData,
  ListProvidersErrors,
  ListProvidersResponses,
  ListRolesData,
  ListRolesErrors,
  ListRolesResponses,
  ListServiceProvidersData,
  ListServiceProvidersErrors,
  ListServiceProvidersResponses,
  ListServicesData,
  ListServicesErrors,
  ListServiceSlotsData,
  ListServiceSlotsErrors,
  ListServiceSlotsResponses,
  ListServicesResponses,
  RescheduleAppointmentData,
  RescheduleAppointmentErrors,
  RescheduleAppointmentResponses,
  UpdateAccountData,
  UpdateAccountErrors,
  UpdateAccountResponses,
  UpdateBlockData,
  UpdateBlockErrors,
  UpdateBlockResponses,
  UpdateCancellationReasonData,
  UpdateCancellationReasonErrors,
  UpdateCancellationReasonResponses,
  UpdateClientData,
  UpdateClientErrors,
  UpdateClientResponses,
  UpdateProviderData,
  UpdateProviderErrors,
  UpdateProviderResponses,
  UpdateProviderScheduleData,
  UpdateProviderScheduleErrors,
  UpdateProviderScheduleResponses,
  UpdateServiceData,
  UpdateServiceErrors,
  UpdateServiceResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get current account
 *
 * Get the account that owns the current token.
 *
 * This endpoint requires:
 *
 * - An account token, or
 * - A platform token with an account ID set via the `X-SavvyCal-Account` header.
 *
 */
export const getCurrentAccount = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCurrentAccountResponses,
    GetCurrentAccountErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/account',
    ...options,
  });
};

/**
 * List accounts
 *
 * List all accounts associated with the current platform (requires a platform token).
 */
export const listAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<ListAccountsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAccountsResponses,
    ListAccountsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/accounts',
    ...options,
  });
};

/**
 * Create account
 *
 * Create a new account (requires a platform token).
 */
export const createAccount = <ThrowOnError extends boolean = false>(
  options?: Options<CreateAccountData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateAccountResponses,
    CreateAccountErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/accounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get account by ID
 *
 * Get the account by ID.
 */
export const getAccountById = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAccountByIdResponses,
    GetAccountByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/accounts/{account_id}',
    ...options,
  });
};

/**
 * Update account
 *
 * Update an existing account.
 */
export const updateAccount = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateAccountResponses,
    UpdateAccountErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/accounts/{account_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List appointments
 *
 * List all appointments that belong to the account.
 */
export const listAppointments = <ThrowOnError extends boolean = false>(
  options?: Options<ListAppointmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAppointmentsResponses,
    ListAppointmentsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/appointments',
    ...options,
  });
};

/**
 * Create appointment
 *
 * Create a new appointment. The time slot for the appointment must be available unless you explicitly disable validation (by setting `validate_slot` to `false` in the request body).
 * You can find available time slots using the [List slots for a service](/api/list-service-slots) endpoint.
 *
 */
export const createAppointment = <ThrowOnError extends boolean = false>(
  options?: Options<CreateAppointmentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateAppointmentResponses,
    CreateAppointmentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/appointments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get appointment
 *
 * Get an existing appointment.
 */
export const getAppointment = <ThrowOnError extends boolean = false>(
  options: Options<GetAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAppointmentResponses,
    GetAppointmentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/appointments/{appointment_id}',
    ...options,
  });
};

/**
 * Cancel appointment
 *
 * Cancel an existing appointment.
 */
export const cancelAppointment = <ThrowOnError extends boolean = false>(
  options: Options<CancelAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CancelAppointmentResponses,
    CancelAppointmentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/appointments/{appointment_id}/cancel',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Confirm appointment
 *
 * Confirm an existing appointment.
 */
export const confirmAppointment = <ThrowOnError extends boolean = false>(
  options: Options<ConfirmAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ConfirmAppointmentResponses,
    ConfirmAppointmentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/appointments/{appointment_id}/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Reschedule appointment
 *
 * Reschedule an existing appointment. The new time slot for the appointment must be available.
 * You can find available time slots using the [List slots for a service](/api/list-service-slots) endpoint.
 *
 */
export const rescheduleAppointment = <ThrowOnError extends boolean = false>(
  options: Options<RescheduleAppointmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RescheduleAppointmentResponses,
    RescheduleAppointmentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/appointments/{appointment_id}/reschedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List blocks
 *
 * List all blocks account-wide or attached to a specific resource type. Blocks are sorted by `start_date` in ascending order (oldest first).
 */
export const listBlocks = <ThrowOnError extends boolean = false>(
  options?: Options<ListBlocksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListBlocksResponses,
    ListBlocksErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/blocks',
    ...options,
  });
};

/**
 * Create block
 *
 * Create a new block.
 */
export const createBlock = <ThrowOnError extends boolean = false>(
  options?: Options<CreateBlockData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateBlockResponses,
    CreateBlockErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/blocks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete block
 *
 * Delete an existing block.
 */
export const deleteBlock = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBlockData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteBlockResponses,
    DeleteBlockErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/blocks/{block_id}',
    ...options,
  });
};

/**
 * Get block
 *
 * Get a block by ID.
 */
export const getBlock = <ThrowOnError extends boolean = false>(
  options: Options<GetBlockData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetBlockResponses,
    GetBlockErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/blocks/{block_id}',
    ...options,
  });
};

/**
 * Update block
 *
 * Update an existing block.
 */
export const updateBlock = <ThrowOnError extends boolean = false>(
  options?: Options<UpdateBlockData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UpdateBlockResponses,
    UpdateBlockErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/blocks/{block_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List cancellation reasons
 *
 * List all cancellation reasons for an account
 */
export const listCancellationReasons = <ThrowOnError extends boolean = false>(
  options?: Options<ListCancellationReasonsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListCancellationReasonsResponses,
    ListCancellationReasonsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/cancellation_reasons',
    ...options,
  });
};

/**
 * Create cancellation reason
 *
 * Create a new cancellation reason in the account.
 */
export const createCancellationReason = <ThrowOnError extends boolean = false>(
  options?: Options<CreateCancellationReasonData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateCancellationReasonResponses,
    CreateCancellationReasonErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/cancellation_reasons',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete cancellation reason
 *
 * Delete an existing cancellation reason.
 */
export const deleteCancellationReason = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCancellationReasonData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteCancellationReasonResponses,
    DeleteCancellationReasonErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/cancellation_reasons/{cancellation_reason_id}',
    ...options,
  });
};

/**
 * Get cancellation reason
 *
 * Get a single cancellation reason by ID.
 */
export const getCancellationReason = <ThrowOnError extends boolean = false>(
  options: Options<GetCancellationReasonData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCancellationReasonResponses,
    GetCancellationReasonErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/cancellation_reasons/{cancellation_reason_id}',
    ...options,
  });
};

/**
 * Update cancellation reason
 *
 * Update an existing cancellation reason.
 */
export const updateCancellationReason = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCancellationReasonData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateCancellationReasonResponses,
    UpdateCancellationReasonErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/cancellation_reasons/{cancellation_reason_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List clients
 *
 * List all clients that belong to the account.
 */
export const listClients = <ThrowOnError extends boolean = false>(
  options?: Options<ListClientsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListClientsResponses,
    ListClientsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/clients',
    ...options,
  });
};

/**
 * Create client
 *
 * Create a new client in the account.
 */
export const createClient = <ThrowOnError extends boolean = false>(
  options?: Options<CreateClientData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateClientResponses,
    CreateClientErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/clients',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete client
 *
 * Deletes an existing client.
 */
export const deleteClient = <ThrowOnError extends boolean = false>(
  options: Options<DeleteClientData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteClientResponses,
    DeleteClientErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/clients/{client_id}',
    ...options,
  });
};

/**
 * Get client
 *
 * Get a single client by ID.
 */
export const getClient = <ThrowOnError extends boolean = false>(
  options: Options<GetClientData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetClientResponses,
    GetClientErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/clients/{client_id}',
    ...options,
  });
};

/**
 * Update client
 *
 * Update an existing client.
 */
export const updateClient = <ThrowOnError extends boolean = false>(
  options: Options<UpdateClientData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateClientResponses,
    UpdateClientErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/clients/{client_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Create dashboard session
 *
 * The Dashboard Sessions API allows you to generate a short-lived session link
 * that grants an account member access to the dashboard without requiring login credentials.
 * This is useful for creating seamless, secure login experiences from external systems or integrations.
 *
 * Before you can generate a session link for someone, you'll need to add them to your SavvyCal account.
 * You can do this by navigating to [Settings → Members & permissions](https://savvycal.app/users)
 * and following the instructions to add a new user. Alternatively, you may use the
 * [Create account user API](https://developers.savvycal.app/api/create-account-user) to add them
 * programmatically.
 *
 * The `user_id` property property can be retrieved from the [List account users API](https://developers.savvycal.app/api/list-account-users),
 * or by copying it directly from the [Settings → Members & permissions](https://savvycal.app/users) page.
 *
 * To sign the user in, redirect the browser to the dashboard session `url` returned in the response.
 *
 * ## Example Flow
 *
 * 1. User clicks a button in your application to "Manage appointments".
 * 2. Your application receives this request and creates a dashboard session via the API.
 * 3. Your application redirects the user to the dashboard session URL.
 * 4. The user is automatically signed in to the dashboard and redirected to the home screen.
 *
 */
export const createDashboardSession = <ThrowOnError extends boolean = false>(
  options?: Options<CreateDashboardSessionData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateDashboardSessionResponses,
    CreateDashboardSessionErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/dashboard_sessions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get current platform
 *
 * Get the platform that owns the current token (requires a platform token).
 *
 */
export const getCurrentPlatform = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentPlatformData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCurrentPlatformResponses,
    GetCurrentPlatformErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/platform',
    ...options,
  });
};

/**
 * List provider schedules
 *
 * List all provider schedules account-wide or for a specific provider.
 */
export const listProviderSchedules = <ThrowOnError extends boolean = false>(
  options?: Options<ListProviderSchedulesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListProviderSchedulesResponses,
    ListProviderSchedulesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/provider_schedules',
    ...options,
  });
};

/**
 * Delete provider schedule
 *
 * Delete an existing provider schedule.
 */
export const deleteProviderSchedule = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProviderScheduleData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProviderScheduleResponses,
    DeleteProviderScheduleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/provider_schedules/{provider_schedule_id}',
    ...options,
  });
};

/**
 * Get provider schedule
 *
 * Get a provider schedule by ID.
 */
export const getProviderSchedule = <ThrowOnError extends boolean = false>(
  options: Options<GetProviderScheduleData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProviderScheduleResponses,
    GetProviderScheduleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/provider_schedules/{provider_schedule_id}',
    ...options,
  });
};

/**
 * Update provider schedule
 *
 * Update an existing provider schedule.
 */
export const updateProviderSchedule = <ThrowOnError extends boolean = false>(
  options?: Options<UpdateProviderScheduleData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UpdateProviderScheduleResponses,
    UpdateProviderScheduleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/provider_schedules/{provider_schedule_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List providers
 *
 * List all providers that belong to the account.
 */
export const listProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ListProvidersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListProvidersResponses,
    ListProvidersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/providers',
    ...options,
  });
};

/**
 * Create provider
 *
 * Create a new provider in the account.
 */
export const createProvider = <ThrowOnError extends boolean = false>(
  options?: Options<CreateProviderData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateProviderResponses,
    CreateProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/providers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Deactivate provider
 *
 * Deactivates an existing provider.
 */
export const deactivateProvider = <ThrowOnError extends boolean = false>(
  options: Options<DeactivateProviderData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeactivateProviderResponses,
    DeactivateProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/providers/{provider_id}',
    ...options,
  });
};

/**
 * Get provider
 *
 * Get a single provider by ID.
 */
export const getProvider = <ThrowOnError extends boolean = false>(
  options: Options<GetProviderData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProviderResponses,
    GetProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/providers/{provider_id}',
    ...options,
  });
};

/**
 * Update provider
 *
 * Update an existing provider.
 */
export const updateProvider = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProviderData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateProviderResponses,
    UpdateProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/providers/{provider_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Create provider schedule
 *
 * Create a new provider schedule.
 */
export const createProviderSchedule = <ThrowOnError extends boolean = false>(
  options?: Options<CreateProviderScheduleData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateProviderScheduleResponses,
    CreateProviderScheduleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/providers/{provider_id}/schedules',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List roles
 *
 * List all roles that belong to the specified account.
 */
export const listRoles = <ThrowOnError extends boolean = false>(
  options?: Options<ListRolesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListRolesResponses,
    ListRolesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/roles',
    ...options,
  });
};

/**
 * Remove service provider
 *
 * Remove a provider from a service
 */
export const deleteServiceProvider = <ThrowOnError extends boolean = false>(
  options: Options<DeleteServiceProviderData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteServiceProviderResponses,
    DeleteServiceProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/service_providers/{service_provider_id}',
    ...options,
  });
};

/**
 * List services
 *
 * List all services for an account
 */
export const listServices = <ThrowOnError extends boolean = false>(
  options?: Options<ListServicesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListServicesResponses,
    ListServicesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services',
    ...options,
  });
};

/**
 * Create service
 *
 * Create a new service in the account.
 */
export const createService = <ThrowOnError extends boolean = false>(
  options?: Options<CreateServiceData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateServiceResponses,
    CreateServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete service
 *
 * Delete an existing service.
 */
export const deleteService = <ThrowOnError extends boolean = false>(
  options: Options<DeleteServiceData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteServiceResponses,
    DeleteServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services/{service_id}',
    ...options,
  });
};

/**
 * Get service
 *
 * Get a single service by ID.
 */
export const getService = <ThrowOnError extends boolean = false>(
  options: Options<GetServiceData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetServiceResponses,
    GetServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services/{service_id}',
    ...options,
  });
};

/**
 * Update service
 *
 * Update an existing service.
 */
export const updateService = <ThrowOnError extends boolean = false>(
  options: Options<UpdateServiceData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateServiceResponses,
    UpdateServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services/{service_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List service providers
 *
 * List all providers associated with a service
 */
export const listServiceProviders = <ThrowOnError extends boolean = false>(
  options: Options<ListServiceProvidersData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ListServiceProvidersResponses,
    ListServiceProvidersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services/{service_id}/providers',
    ...options,
  });
};

/**
 * Add provider to service
 *
 * Associate a provider with a service
 */
export const createServiceProvider = <ThrowOnError extends boolean = false>(
  options: Options<CreateServiceProviderData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateServiceProviderResponses,
    CreateServiceProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services/{service_id}/providers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List slots for a service
 *
 * List all available slots for a service in a specific time range
 */
export const listServiceSlots = <ThrowOnError extends boolean = false>(
  options: Options<ListServiceSlotsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ListServiceSlotsResponses,
    ListServiceSlotsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/services/{service_id}/slots',
    ...options,
  });
};

/**
 * List account users
 *
 * List all users that belong to the specified account.
 */
export const listAccountUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListAccountUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAccountUsersResponses,
    ListAccountUsersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/users',
    ...options,
  });
};

/**
 * Create account user
 *
 * Create a new user in the specified account.
 */
export const createAccountUser = <ThrowOnError extends boolean = false>(
  options?: Options<CreateAccountUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateAccountUserResponses,
    CreateAccountUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/v1/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};
